// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuK8ZUrYY8PQk5Ol-ucxU7C2_kmRFPaXs',
    appId: '1:698275972508:web:40e7b72631cad6a1dff459',
    messagingSenderId: '698275972508',
    projectId: 'overture-6c8e3',
    authDomain: 'overture-6c8e3.firebaseapp.com',
    storageBucket: 'overture-6c8e3.firebasestorage.app',
    measurementId: 'G-FX0YLGBB3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6hxdWhw5paOxaOMOtpft3ifqN8-0DVmY',
    appId: '1:698275972508:android:d0f3bd0595ea1aa5dff459',
    messagingSenderId: '698275972508',
    projectId: 'overture-6c8e3',
    storageBucket: 'overture-6c8e3.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt36WUl5Kq9mSDC_wdv2SPH_KOl6oD2B4',
    appId: '1:698275972508:ios:17a08115d9cc65bddff459',
    messagingSenderId: '698275972508',
    projectId: 'overture-6c8e3',
    storageBucket: 'overture-6c8e3.firebasestorage.app',
    iosBundleId: 'com.example.overtureQrScouting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuK8ZUrYY8PQk5Ol-ucxU7C2_kmRFPaXs',
    appId: '1:698275972508:web:be5ef1b28f86b728dff459',
    messagingSenderId: '698275972508',
    projectId: 'overture-6c8e3',
    authDomain: 'overture-6c8e3.firebaseapp.com',
    storageBucket: 'overture-6c8e3.firebasestorage.app',
    measurementId: 'G-3QBPBV45GH',
  );
}
