// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyTKK5YAaYv7OzzAkpMZaistz9Vnbqmzo',
    appId: '1:878951145860:web:abeb6da200d510a2d9fdd1',
    messagingSenderId: '878951145860',
    projectId: 'ftcovertureqr',
    authDomain: 'ftcovertureqr.firebaseapp.com',
    storageBucket: 'ftcovertureqr.firebasestorage.app',
    measurementId: 'G-RSPJHLQVKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSDqjfaMeVkiOkAeQakYkw3VFZAyHvywY',
    appId: '1:878951145860:android:21a3089d3ba4de9ad9fdd1',
    messagingSenderId: '878951145860',
    projectId: 'ftcovertureqr',
    storageBucket: 'ftcovertureqr.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfeRtS4xlspTltg9dowCdKtcVyGOrAiEM',
    appId: '1:878951145860:ios:a9d25e3285679037d9fdd1',
    messagingSenderId: '878951145860',
    projectId: 'ftcovertureqr',
    storageBucket: 'ftcovertureqr.firebasestorage.app',
    iosBundleId: 'com.example.overtureQrScouting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyTKK5YAaYv7OzzAkpMZaistz9Vnbqmzo',
    appId: '1:878951145860:web:b19f0db916e11f3fd9fdd1',
    messagingSenderId: '878951145860',
    projectId: 'ftcovertureqr',
    authDomain: 'ftcovertureqr.firebaseapp.com',
    storageBucket: 'ftcovertureqr.firebasestorage.app',
    measurementId: 'G-ZXXDM33T97',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfeRtS4xlspTltg9dowCdKtcVyGOrAiEM',
    appId: '1:878951145860:ios:a9d25e3285679037d9fdd1',
    messagingSenderId: '878951145860',
    projectId: 'ftcovertureqr',
    storageBucket: 'ftcovertureqr.firebasestorage.app',
    iosBundleId: 'com.example.overtureQrScouting',
  );

}